# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blaising Grattles
tagline:             'Blaise Gratton lobs blog blabber'
description:         'Currently studying at Nashville Software School. A place for coding, classics, and music. Powered by <a href="https://github.com/jekyll/jekyll" target="_blank">Jekyll</a>'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
