# Site settings
title: Blaise Gratton
email: blaisegratton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The projects and musings of an aspiring software developer. Student by day, musician by night, classicist by trade. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: BlaiseGratton
github_username:  blaisegratton

# Build settings
markdown: kramdown
